#!/bin/bash  

##create cert dir
sudo mkdir ~/.config/hexchat/certs

##create fsociety cert
sudo openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:4096 -keyout ~/.config/hexchat/certs/fsocietySASL.pem -out ~/.config/hexchat/cert$

##edit fsociety cert
sudo openssl x509 -in ~/.config/hexchat/certs/client.pem -outform der | sha1sum -b | cut -d \  -f1
